---

- name: "Create Directories"
  file:
    state: "directory"
    path: "/etc/sysconfig"
  tags:
    - "lobalancer"

- name: "Apply Templates"
  template:
    dest: "/etc/sysconfig/lobalancer@{{ item.ipv4 | ipaddr('address') }}.env"
    src:  "lobalancer@.env.j2"
  vars:
    jmespath: "[{% for var in (lookup('varnames', '^lobalancer_.+') | join).split(',') %}{{ var }}{{ ',' if not loop.last else '' }}{% endfor %}][]"
  with_items: "{{ ([]) if jmespath == '[][]' else (vars | to_json | from_json | json_query(jmespath)) }}"
  notify: "lobalancer-restart"
  tags:
    - "lobalancer"

- name: "Start and Enable Services"
  service:
    name:          "lobalancer@{{ item.name | default(item.ipv4 | ipaddr('address')) }}.service"
    enabled:       "yes"
    state:         "started"
    daemon_reload: "yes"
  vars:
    jmespath: "[{% for var in (lookup('varnames', '^lobalancer_.+') | join).split(',') %}{{ var }}{{ ',' if not loop.last else '' }}{% endfor %}][]"
  with_items: "{{ ([]) if jmespath == '[][]' else (vars | to_json | from_json | json_query(jmespath)) }}"
  tags:
    - "lobalancer"
