---
- name: "Restart Timer"
  systemd:
    daemon_reload: "yes"
    name:          "lobalancer@{{ item.name | default(item.ipv4 | ipaddr('address')) }}.timer"
    state:         "restarted"
  with_items: "{{ lobalancer }}"
  listen: "lobalancer-restart"
